const router = require('express').Router();
const c = require('./review.controller');
const v = require('./review.validator');
const validate = require('../../common/middleware/validate.middleware');
const { requireAuth, optionalAuth } = require('../../common/middleware/auth.middleware');
const { writeLimiter } = require('../../common/middleware/rate-limit.middleware');
const asyncHandler = require('../../common/utils/async-handler');
router.get('/reviews', asyncHandler(c.listCommunity));
router.post('/reviews', requireAuth, writeLimiter, asyncHandler(c.createCommunity));
router.get('/reviews/:id', v.id, validate, asyncHandler(c.communityDetail));
router.get('/places/:id/reviews', v.id, validate, asyncHandler(c.listByPlace));
router.post('/places/:id/reviews', requireAuth, writeLimiter, v.create, validate, asyncHandler(c.create));
router.put('/reviews/:id', requireAuth, writeLimiter, v.update, validate, asyncHandler(c.update));
router.delete('/reviews/:id', requireAuth, v.id, validate, asyncHandler(c.remove));
router.post('/reviews/:id/vote', requireAuth, writeLimiter, v.id, validate, asyncHandler(c.vote));
router.post('/reviews/:id/report', optionalAuth, writeLimiter, v.id, validate, asyncHandler(c.report));
module.exports = router;
