const router = require('express').Router();
const c = require('./route.controller');
const v = require('./route.validator');
const validate = require('../../common/middleware/validate.middleware');
const asyncHandler = require('../../common/utils/async-handler');
router.get('/', asyncHandler(c.listRoutes));
router.get('/:id', v.routeId, validate, asyncHandler(c.getRoute));
router.get('/:id/stops', v.routeId, validate, asyncHandler(c.getRouteStops));
router.get('/:id/buses', v.routeId, validate, asyncHandler(c.getRouteBuses));
module.exports = router;
