const router = require('express').Router();
const c = require('./tourism.controller');
const v = require('./tourism.validator');
const validate = require('../../common/middleware/validate.middleware');
const { requireAuth } = require('../../common/middleware/auth.middleware');
const asyncHandler = require('../../common/utils/async-handler');
router.get('/categories', asyncHandler(c.categories));
router.get('/places', v.search, validate, asyncHandler(c.list));
router.get('/places/search', v.search, validate, asyncHandler(c.search));
router.get('/places/recommended', v.search, validate, asyncHandler(c.recommended));
router.get('/places/near', v.search, validate, asyncHandler(c.near));
router.get('/places/:id', v.id, validate, asyncHandler(c.detail));
router.get('/places/:id/bus-suggestion', v.id, validate, asyncHandler(c.busSuggestion));
router.get('/places/:id/nearby-stops', v.id, validate, asyncHandler(c.nearbyStops));
router.get('/places/:id/reviews', v.id, validate, asyncHandler(c.reviews));
router.post('/places/:id/favorite', requireAuth, v.id, validate, asyncHandler(c.favorite));
router.delete('/places/:id/favorite', requireAuth, v.id, validate, asyncHandler(c.unfavorite));
router.post('/places/:id/save', requireAuth, v.id, validate, asyncHandler(c.favorite));
router.delete('/places/:id/save', requireAuth, v.id, validate, asyncHandler(c.unfavorite));
router.post('/favorites/places/:id', requireAuth, v.id, validate, asyncHandler(c.favorite));
router.delete('/favorites/places/:id', requireAuth, v.id, validate, asyncHandler(c.unfavorite));
router.get('/favorites/places', requireAuth, asyncHandler(c.favorites));
module.exports = router;
