const router = require('express').Router();
const c = require('./auth.controller');
const v = require('./auth.validator');
const validate = require('../../common/middleware/validate.middleware');
const asyncHandler = require('../../common/utils/async-handler');
const { authLimiter } = require('../../common/middleware/rate-limit.middleware');
router.post('/register', authLimiter, v.register, validate, asyncHandler(c.register));
router.post('/login', authLimiter, v.login, validate, asyncHandler(c.login));
router.post('/refresh-token', authLimiter, v.refresh, validate, asyncHandler(c.refresh));
router.post('/logout', asyncHandler(c.logout));
module.exports = router;
