const router = require('express').Router();
const c = require('./report.controller');
const v = require('./report.validator');
const validate = require('../../common/middleware/validate.middleware');
const { optionalAuth, requireAuth } = require('../../common/middleware/auth.middleware');
const { requireRole } = require('../../common/middleware/role.middleware');
const { writeLimiter } = require('../../common/middleware/rate-limit.middleware');
const asyncHandler = require('../../common/utils/async-handler');
router.post('/', optionalAuth, writeLimiter, v.create, validate, asyncHandler(c.create));
router.get('/', requireAuth, requireRole('admin','moderator'), asyncHandler(c.list));
router.put('/:id/status', requireAuth, requireRole('admin','moderator'), v.status, validate, asyncHandler(c.updateStatus));
module.exports = router;
