const router = require('express').Router();
const c = require('./community.controller');
const v = require('./community.validator');
const validate = require('../../common/middleware/validate.middleware');
const { requireAuth, optionalAuth } = require('../../common/middleware/auth.middleware');
const { writeLimiter } = require('../../common/middleware/rate-limit.middleware');
const asyncHandler = require('../../common/utils/async-handler');
router.get('/posts', asyncHandler(c.list));
router.post('/posts', requireAuth, writeLimiter, v.create, validate, asyncHandler(c.create));
router.get('/posts/:id', v.id, validate, asyncHandler(c.detail));
router.put('/posts/:id', requireAuth, writeLimiter, v.id, validate, asyncHandler(c.update));
router.delete('/posts/:id', requireAuth, v.id, validate, asyncHandler(c.remove));
router.post('/posts/:id/comments', requireAuth, writeLimiter, v.comment, validate, asyncHandler(c.comment));
router.post('/posts/:id/vote', requireAuth, writeLimiter, v.id, validate, asyncHandler(c.vote));
module.exports = router;
