const router = require('express').Router();
const c = require('./trip.controller');
const v = require('./trip.validator');
const validate = require('../../common/middleware/validate.middleware');
const { requireAuth, optionalAuth } = require('../../common/middleware/auth.middleware');
const { writeLimiter } = require('../../common/middleware/rate-limit.middleware');
const asyncHandler = require('../../common/utils/async-handler');
router.get('/options', asyncHandler(c.options));
router.post('/generate', optionalAuth, writeLimiter, v.generate, validate, asyncHandler(c.generate));
router.get('/my', requireAuth, asyncHandler(c.my));
router.get('/:id', requireAuth, v.id, validate, asyncHandler(c.detail));
router.delete('/:id', requireAuth, v.id, validate, asyncHandler(c.remove));
module.exports = router;
